# prometheus.yaml
global:
  scrape_interval: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: vllm
    static_configs:
      - targets:
          - 'vllm:8000'
  - job_name: dcgm-exporter
    static_configs:
      - targets:
          - 'dcgm-exporter:9400'
  - job_name: node-exporter
    static_configs:
      - targets:
          - 'node-exporter:9100'

